import React from 'react';
import Layout from '../../components/Layout';
import { Code, GitBranch, ShieldCheck, Users, Wallet, ArrowRight, Layers, Lock, Zap } from 'lucide-react';
import { Link } from 'react-router-dom';

export default function DevelopersProgram() {
    return (
        <Layout>
            <div className="bg-[#050505] text-white min-h-screen font-sans selection:bg-brand selection:text-white">

                {/* Hero Section */}
                <div className="relative py-32 px-6 overflow-hidden">
                    <div className="absolute inset-0 bg-brand/5 rotate-12 scale-150 rounded-full blur-[100px] opacity-20 pointer-events-none" />
                    <div className="max-w-4xl mx-auto text-center relative z-10">
                        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-brand/10 border border-brand/20 text-brand text-xs font-bold uppercase tracking-widest mb-8">
                            <Code size={14} />
                            Developers Program
                        </div>
                        <h1 className="text-6xl md:text-7xl font-black mb-6 tracking-tighter uppercase leading-none">
                            Build the <span className="text-brand">Future</span>.<br />
                            Own the <span className="text-white">Value</span>.
                        </h1>
                        <p className="text-xl md:text-2xl text-white/60 leading-relaxed font-light max-w-2xl mx-auto">
                            Join the Northfield Solidarity ecosystem. Build powerful engines, retained equity, and autonomous revenue streams.
                        </p>
                    </div>
                </div>

                {/* Core Pillars */}
                <div className="max-w-6xl mx-auto px-6 grid md:grid-cols-3 gap-8 mb-32">
                    <ProgramCard
                        icon={GitBranch}
                        title="51/49 Equity Split"
                        desc="A fair foundation. Northfield Solidarity retains 51% for ecosystem security and growth. You, the creator, own 49% of the equity in your project."
                    />
                    <ProgramCard
                        icon={Users}
                        title="Your Equity, Your Choice"
                        desc="Power to the people. You hold the absolute power to distribute your 49% stake to any user, contributor, or entity as you see fit."
                    />
                    <ProgramCard
                        icon={Wallet}
                        title="Revenue Follows Ownership"
                        desc="Automated wealth distribution. All revenue streams generated by your project are split automatically according to the IP ownership ratio."
                    />
                </div>

                {/* Technical Details Section */}
                <div className="bg-[#0f0f0f] border-y border-white/5 py-32">
                    <div className="max-w-6xl mx-auto px-6 flex flex-col md:flex-row gap-16 items-center">
                        <div className="flex-1 space-y-8">
                            <h2 className="text-4xl font-bold uppercase tracking-tight">The Protocol</h2>
                            <p className="text-lg text-white/60 leading-relaxed">
                                Our developer program is not just a policy; it's a protocol. By building on the Northfield Solidarity Operating System (NS-OS), you gain access to a unified identity layer, secure payments, and a ready-made audience.
                            </p>

                            <ul className="space-y-4">
                                <ProtocolItem icon={Layers} text="Modular Engine Architecture" />
                                <ProtocolItem icon={Lock} text="Iron-Clad Security & Identity" />
                                <ProtocolItem icon={Zap} text="Instant Revenue Settlement" />
                            </ul>

                            <div className="pt-8">
                                <Link to="/developers/access" className="inline-flex items-center gap-2 px-8 py-4 bg-brand text-black font-bold rounded hover:bg-white transition-colors">
                                    ACCESS DEV CONSOLE <ArrowRight size={18} />
                                </Link>
                            </div>
                        </div>
                        <div className="flex-1 relative">
                            {/* Visual Representation of Split */}
                            <div className="relative aspect-square max-w-md mx-auto">
                                <div className="absolute inset-0 bg-gradient-to-tr from-brand/20 to-blue-500/20 rounded-full blur-3xl" />
                                <div className="relative z-10 border border-white/10 bg-black/50 backdrop-blur-md rounded-2xl p-8 h-full flex flex-col justify-center">
                                    <div className="flex items-center justify-between mb-12">
                                        <div className="text-center">
                                            <div className="text-5xl font-black text-brand mb-2">51%</div>
                                            <div className="text-xs uppercase tracking-widest text-white/40">NS DAO</div>
                                        </div>
                                        <div className="h-px bg-white/20 flex-1 mx-8" />
                                        <div className="text-center">
                                            <div className="text-5xl font-black text-white mb-2">49%</div>
                                            <div className="text-xs uppercase tracking-widest text-white/40">Creator</div>
                                        </div>
                                    </div>
                                    <div className="space-y-4">
                                        <div className="flex justify-between text-sm border-b border-white/10 pb-2">
                                            <span className="text-white/60">Governance Rights</span>
                                            <span className="text-brand">Joint</span>
                                        </div>
                                        <div className="flex justify-between text-sm border-b border-white/10 pb-2">
                                            <span className="text-white/60">IP Ownership</span>
                                            <span className="text-brand">Shared</span>
                                        </div>
                                        <div className="flex justify-between text-sm border-b border-white/10 pb-2">
                                            <span className="text-white/60">Distribution Rights</span>
                                            <span className="text-white">Creator Controlled (49%)</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </Layout>
    );
}

function ProgramCard({ icon: Icon, title, desc }) {
    return (
        <div className="p-8 border border-white/10 rounded-xl bg-white/5 hover:bg-white/10 transition-colors group">
            <div className="w-12 h-12 bg-black rounded-lg flex items-center justify-center mb-6 group-hover:scale-110 transition-transform">
                <Icon size={24} className="text-brand" />
            </div>
            <h3 className="text-xl font-bold mb-4">{title}</h3>
            <p className="text-white/50 leading-relaxed">{desc}</p>
        </div>
    );
}

function ProtocolItem({ icon: Icon, text }) {
    return (
        <li className="flex items-center gap-3 text-white/80">
            <div className="p-2 rounded bg-white/5 text-brand">
                <Icon size={16} />
            </div>
            {text}
        </li>
    );
}
